name: Trigger auto deployment for container-app-p5l7cnc3mvmfi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-p5l7cnc3mvmfi-AutoDeployTrigger-0fdd2f76-813d-4275-8862-6a8e13eaee8e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPP5L7CNC3MVMFI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPP5L7CNC3MVMFI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPP5L7CNC3MVMFI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPP5L7CNC3MVMFI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPP5L7CNC3MVMFI_REGISTRY_PASSWORD }}
          containerAppName: container-app-p5l7cnc3mvmfi
          resourceGroup: miabetodo0707bf90
          imageToBuild: default/container-app-p5l7cnc3mvmfi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


